### ISSUE TITLE
Impossible de passer le jour 4

### ISSUE THREAD

**Issue by ipante** [glitch1312/Fix-It#44]
La nouvelle clientèle n'arrive pas.
A l'extérieur, personne ne me propose d'activité.

**Comment by glitch1312** [comment]
pouvez vous prendre les flyers? ils sont sur la table du milieu

**Comment by ipante** [comment]
exact, je viens de le constater : ceci dit, je pense qu'il faudrait une aide (pop-up textuel) ou une meilleure mise en évidence de l'action (texte clignotant pour "prendre" le flyer?)

J'avais déjà rencontré le même problème à l'époque.
